INSERT INTO public.applicationcategory(  application, category)  VALUES ('AOL', 'Web Browser');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Amazon Shopping', 'Shopping');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Android In Call UI', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Badoo', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Brave Browser', 'Web Browser');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Calculator', 'Productivity');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Calendar', 'Productivity');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Calorie Counter', 'Health');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Camera', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Clean Master', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Clock', 'Productivity');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Contacts', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Discord', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Facebook', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Facebook Messenger', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Faceu', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Flipboard Briefing', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Gmail', 'Productivity');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Google', 'Web Browser');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Google Chrome', 'Web Browser');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Google Drive', 'Productivity');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Google Photos', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Google Play Music', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Google Play Store', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Hangouts', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Hulu', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Ibotta', 'Finances');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Instagram', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Kik', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Lucktastic', 'Games');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('MUIQ Survey App', 'Miscellaneous');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Maps', 'Transport');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Messages', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Messaging', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Messenger Lite', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('MetroZone', 'Miscellaneous');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Microsoft Bing Search', 'Web Browser');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Microsoft Outlook', 'Productivity');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Netflix', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('OfferUp', 'Shopping');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Pandora Music', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('PayPal Mobile Cash', 'Finances');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Phone', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Pinterest', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Podcast Addict', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Receipt Hog', 'Finances');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Reddit', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Reward Stash', 'Shopping');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Robinhood', 'Finances');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Samsung Email', 'Productivity');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Samsung Gallery', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Samsung Internet Browser', 'Web Browser');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Samsung Notes', 'Productivity');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Samsung Pay', 'Finances');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Settings', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Slidejoy', 'Miscellaneous');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Snapchat', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Spotify Music', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('SurveyCow', 'Miscellaneous');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Swagbucks', 'Miscellaneous');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('S’more', 'Finances');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Telegram', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Telegram X', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('TextNow', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('The PCH App', 'Finances');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Twitter', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Verizon Messages', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Walmart', 'Shopping');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('WeChat', 'Finances');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('WhatsApp Messenger', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Words With Friends 2', 'Games');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('Yahoo Mail', 'Productivity');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('YouTube', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('eBay', 'Shopping');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('imo', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('android', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('co.trebbble.android.wind.f2g', 'Finances');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.Slack', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.accuweather.android', 'Miscellaneous');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.alarmclock.xtreme.free', 'Miscellaneous');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.alexso.alarmclock', 'Miscellaneous');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.alibaba.aliexpresshd', 'Shopping');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.amazon.mShop.android.shopping', 'Shopping');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.android.bluetooth', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.android.chrome', 'Web Browser');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.android.deskclock', 'Miscellaneous');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.android.dialer', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.android.email', 'Productivity');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.android.incallui', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.android.mediacenter', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.android.mms', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.android.phone', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.android.providers.downloads', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.android.server.telecom', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.android.settings', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.android.systemui', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.android.vending', 'Finances');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.android.vending.billing.InAppBillingService.COIN', 'Finances');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.banana4apps.evolution', 'Games');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.booking', 'Shopping');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.cardgame.solitaire.fishdom', 'Games');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.cashitapp.app.jokesphone', 'Games');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.chargedmonkey.whatthehen', 'Games');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.citymapper.app.release', 'Transport');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.cleanmaster.mguard', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.contextlogic.wish', 'Shopping');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.ea.games.simsfreeplay_row', 'Games');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.ebay.mobile', 'Shopping');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.eset.ems2.gp', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.estrongs.android.pop', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.facebook.appmanager', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.facebook.katana', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.facebook.orca', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.fastemulator.gbafree', 'Games');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.globalegrow.app.gearbest', 'Shopping');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.google.android.GoogleCamera', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.google.android.apps.docs', 'Productivity');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.google.android.apps.fitness', 'Health');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.google.android.apps.inbox', 'Productivity');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.google.android.apps.magazines', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.google.android.apps.maps', 'Transport');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.google.android.apps.messaging', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.google.android.apps.photos', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.google.android.calendar', 'Miscellaneous');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.google.android.deskclock', 'Miscellaneous');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.google.android.dialer', 'Miscellaneous');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.google.android.gm', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.google.android.gms', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.google.android.googlequicksearchbox', 'Web Browser');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.google.android.keep', 'Productivity');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.google.android.music', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.google.android.youtube', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.grindrapp.android', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.hsv.freeadblockerbrowser', 'Web Browser');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.huawei.android.FMRadio', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.huawei.health', 'Health');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.huawei.hidisk', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.huawei.screenrecorder', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.huawei.systemmanager', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.imangi.templerun2', 'Games');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.infinitygames.connection', 'Games');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.instagram.android', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.instfollowers', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.iudesk.android.photo.editor', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.joelapenna.foursquared', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.lge.appbox.client', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.lge.appwidget.flashlight', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.lge.clock', 'Miscellaneous');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.lge.eula', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.lge.fmradio', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.lge.keepscreenon', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.lge.lginstallservies', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.lge.lifetracker', 'Health');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.lge.music', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.lilithgame.sgame.gp.oss', 'Games');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.linkedin.android', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.m11pets.elevenpets', 'Miscellaneous');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.maxmpz.audioplayer', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.melodis.midomiMusicIdentifier.freemium', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.microsoft.office.outlook', 'Productivity');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.mobisystems.office', 'Productivity');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.mobrog.surveys.app01', 'Miscellaneous');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.motorola.actions', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.motorola.fmplayer', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.mtsfreegames.shipdrivinggames', 'Games');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.netflix.mediaclient', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.oneplus.deskclock', 'Miscellaneous');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.oneplus.screenshot', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.paypal.android.p2pmobile', 'Finances');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.perblue.disneyheroes', 'Games');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.philips.lighting.hue2', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.pinterest', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.planetromeo.android.app', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.pleasantapps.unfollowers', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.pockee', 'Miscellaneous');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.popularapp.periodcalendar', 'Health');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.popularapp.thirtydayfitnesschallenge', 'Health');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.revolut.revolut', 'Finances');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.rhmsoft.fm', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.runtastic.android', 'Health');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.samsung.android.app.scrollcapture', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.samsung.android.incallui', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.samsung.android.lool', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.samsung.android.messaging', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.scee.psxandroid', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.sec.android.app.clockpackage', 'Miscellaneous');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.sec.android.app.fm', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.sec.android.app.music', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.sec.android.app.samsungapps', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.sec.android.app.voicenote', 'Productivity');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.sec.android.daemonapp', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.sec.android.pagebuddynotisvc', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.shazam.android', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.skype.raider', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.socialnmobile.dictapps.notepad.color.note', 'Productivity');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.sonyericsson.android.omacp', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.sonyericsson.conversations', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.sonyericsson.music', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.sonyericsson.organizer', 'Productivity');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.sonyericsson.updatecenter', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.sonymobile.entrance', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.sonymobile.moviecreator.rmm', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.sonymobile.runtimeskinning.core', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.sonymobile.storagechecker', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.soundcloud.android', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.spotify.music', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.tinder', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.topjohnwu.magisk', 'Miscellaneous');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.tumblr', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.tux.client', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.twitter.android', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.utorrent.client', 'Miscellaneous');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.valvesoftware.android.steam.community', 'Games');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.venturegeeks.efood', 'Shopping');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.viber.voip', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.weplaydots.twodotsandroid', 'Games');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.whatsapp', 'Social');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.wssyncmldm', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.yazio.android', 'Health');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.yeelight.cherry', 'Miscellaneous');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.zaful', 'Shopping');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('com.zeptolab.cats.google', 'Games');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('de.axelspringer.yana.zeropage', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('de.digame.esc', 'Games');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('de.fun2code.android.pawserver', 'System');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('eu.nordeus.topeleven.android', 'Games');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('flipboard.app', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('flipboard.boxer.app', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('gr.coral.shellsmart', 'Shopping');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('gr.cosmote.myaccount.widget', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('gr.cosmote.whatsup', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('gr.offradio2', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('homeworkout.homeworkouts.noequipment', 'Health');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('me.bluemail.mail', 'Productivity');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('net.oneplus.weather', 'Miscellaneous');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('nickagas.com.phusicsupatrasnews', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('org.videolan.vlc', 'Entertainment');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('pl.idreams.SkyForceReloaded2016', 'Games');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('sixpack.sixpackabs.absworkout', 'Health');
INSERT INTO public.applicationcategory(  application, category)  VALUES ('yqtrack.app', 'Miscellaneous');